// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoU4K8QXvQwfKbNRQpnoIH8CbYBpHiis8',
    appId: '1:183711894078:web:13e2ee8961df0a4dd1df6f',
    messagingSenderId: '183711894078',
    projectId: 'to-do-app-b0000',
    authDomain: 'to-do-app-b0000.firebaseapp.com',
    storageBucket: 'to-do-app-b0000.firebasestorage.app',
    measurementId: 'G-6K0G038PH8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx6-2l73Ibhvl2a7BOBT3yHMkCsOUs3Fo',
    appId: '1:183711894078:android:2cb472737817b339d1df6f',
    messagingSenderId: '183711894078',
    projectId: 'to-do-app-b0000',
    storageBucket: 'to-do-app-b0000.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWQLHomGi_9srnvU5EZDF_Db4NY-pVBvk',
    appId: '1:183711894078:ios:42eca67cc7cc449ad1df6f',
    messagingSenderId: '183711894078',
    projectId: 'to-do-app-b0000',
    storageBucket: 'to-do-app-b0000.firebasestorage.app',
    iosBundleId: 'com.example.toDoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWQLHomGi_9srnvU5EZDF_Db4NY-pVBvk',
    appId: '1:183711894078:ios:42eca67cc7cc449ad1df6f',
    messagingSenderId: '183711894078',
    projectId: 'to-do-app-b0000',
    storageBucket: 'to-do-app-b0000.firebasestorage.app',
    iosBundleId: 'com.example.toDoList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoU4K8QXvQwfKbNRQpnoIH8CbYBpHiis8',
    appId: '1:183711894078:web:bdb26a95db998779d1df6f',
    messagingSenderId: '183711894078',
    projectId: 'to-do-app-b0000',
    authDomain: 'to-do-app-b0000.firebaseapp.com',
    storageBucket: 'to-do-app-b0000.firebasestorage.app',
    measurementId: 'G-8EFX44Z5GK',
  );
}
